### ISSUE TITLE
Refactoring: Centralize SQL connection handling into central crate

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#109]
Currently we have a lot of code duplication between the differnt SQL connectors that we have. We should create a new crate in our `libs` folder that compose `prisma-query` and all database drivers into a neat abstraction that can be used in all of our SQL connectors.

@do4gr and I disovered that when implementing the SQL introspection tests that required us to copy a ton of code from the SQL migration connector.

**Comment by mavilein** [comment]
This is something that @tomhoule could tackle.

**Comment by tomhoule** [comment]
Depending on when we tackle that problem, we may want to do it more or less at the same time as the move to asynchronous database access. prisma-query has lots of breaking changes in the async-await branch, so it will force us to rewrite the SQL connection handling anyway.

**Comment by tomhoule** [comment]
This is already partially done in master. Once https://github.com/prisma/prisma-engine/pull/162 is merged, I think we can consider this issue closed.
