### ISSUE TITLE
Introspection Engine: test against our collection of database schema examples

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#122]
We have a created a collection of database schema examples that exist. We should test our introspection against these schemas to make sure the introspection succeeds. We should use those introspection results as a foundation for a discussion with product whether we can ship this feature.

**Comment by do4gr** [comment]
I checked out most of the sample schemata and collected some thoughts about cases introspection can currently not handle here https://github.com/prisma/specs/issues/304.
