### ISSUE TITLE
Migration Engine: Implement Errors Spec

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#130]
This work package is part of this [epic](https://github.com/prisma/prisma-engine/issues/128).

Please supply a task list in a comment.

**Comment by tomhoule** [comment]
Work in progress PR: https://github.com/prisma/prisma-engine/pull/142

It is getting very big, so I will try to split it up when it's ready.

**Comment by tomhoule** [comment]
The PR is ready for review. I handed over the branch to @timsuchanek  so he can give feedback from his side and start implementing the frontend part if everything is good.

**Comment by tomhoule** [comment]
I think we can close this since the engine PR is merged and the frontend has been adjusted to the new errors.
