### ISSUE TITLE
Query Engine: Implement Errors Spec

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#132]
This work package is part of this [epic](https://github.com/prisma/prisma-engine/issues/128).

Please supply a task list in a comment.

**Comment by tomhoule** [comment]
Status update: there is a PR for this.

**Comment by tomhoule** [comment]
I think this can be closed, unless we consider this finished only if we test for all the error types in the spec. Currently some are blocked on quaint issues. I could write down a recap here.
