### ISSUE TITLE
Libs: Implement `user-facing-errors` crate

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#133]
This work package is part of this [epic](https://github.com/prisma/prisma-engine/issues/128).

Please supply a task list in a comment.

**Comment by tomhoule** [comment]
WIP PR: https://github.com/prisma/prisma-engine/pull/142

This is currently conflated with its usage in the migration-engine because I didn't want to validate the crate's design by usage.

**Comment by tomhoule** [comment]
Status update: the PR is ready to merge, but we will wait until the frontend is changed to handle the JSON errors we return now.

**Comment by tomhoule** [comment]
I think we can close this since the engine PR is merged and the frontend has been adjusted to the new errors.
