### ISSUE TITLE
Application logic invariant error

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-engine#151]
The query-engine allows invalid data to be inserted.
Concretely: While model `A` has a required relation to model `B`, query-engine allows inserting a model `A` record, without providing `B`.

Querying that data then fails.

Full Repro: https://github.com/timsuchanek/prisma-engine-255-repro

It will either end up in 
```
Application logic invariant error: received null value for field blog which may not be null in query-engine/core/src/response_ir/internal.rs:228:26
```

![image](https://user-images.githubusercontent.com/1094804/68137354-1e612080-ff27-11e9-8a9c-30595fe4c938.png)

**Comment by dpetrick** [comment]
Awaiting confirmation that this is still an issue.

**Comment by dpetrick** [comment]
Confirmed still an issue but with different error now. I will proceed to check if this error is sufficient (it's originating from the connector), or if we should throw a different, more descriptive error.

**Comment by dpetrick** [comment]
Considered a sufficiently descriptive error with Preview-17. Closing this issue.
