### ISSUE TITLE
Query engine: integer fields return floats

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-engine#160]
Defining an integer in the schema and querying for it returns a float.

For example:

```groovy
model User {
	id  String  @id @default(cuid())
	age Int
}
```

Sending a query

```graphql
query {
  findManyUser {
    id
    age
  }
}
```

returns

```json
{
  "data": {
    "findManyUser": [
      {
        "id": "id",
        "age": 5.0
      }
    ]
  }
}
```

It should return an integer instead, e.g. `"age": 5`.

**Comment by pantharshit00** [comment]
Related photonjs issue: https://github.com/prisma/photonjs/issues/279

**Comment by dpetrick** [comment]
Fixed.

**Comment by janpio** [comment]
Can you confirm @Luca pls?

**Comment by steebchen** [comment]
I can confirm that this now works as intended. Now just waiting for a CLI release.
