### ISSUE TITLE
Compare Introspection Implementations: Rust vs. Typescript

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#171]
We will run both implementations against those [schemas](https://github.com/prisma/database-schema-examples) and compile an overview of their differences in output. We will use this overview to decide whether we will switch the CLI to the new Rust implementation.

**Comment by do4gr** [comment]
The overview of the differences can now be found in the specs repo, issues 309-313.

**Comment by janpio** [comment]
https://github.com/prisma/specs/issues/309
https://github.com/prisma/specs/issues/310
https://github.com/prisma/specs/issues/311
https://github.com/prisma/specs/issues/312
https://github.com/prisma/specs/issues/313
