### ISSUE TITLE
EPIC: Native Scalar Lists

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#192]
**Spec**: The relevant part of the spec on the Prisma Schema Language can be found [here](https://github.com/prisma/specs/tree/master/schema#list-types).

**Description**: We want to change the implementation of scalar lists so that only connectors that support them natively will offer this feature.

## Links to actual Work Packages
* [Datamodel Parser](https://github.com/prisma/prisma-engine/issues/193)
* [Migration Engine](https://github.com/prisma/prisma-engine/issues/194)
* [Query Engine](https://github.com/prisma/prisma-engine/issues/195)
* [Introspection Engine](https://github.com/prisma/prisma-engine/issues/196)

**Comment by mavilein** [comment]
## Initial Breakdown of Work Packages
* Datamodel Parser
  * only the Postgres connector must allow to use scalar lists
* Migration Engine
  * the logic for separate tables for scalar lists must be removed
  * instead we must use array columns for Postgres
* Query Engine
  * the logic for separate tables for scalar lists must be removed
  * remove `get_scalar_list_values` from the connector interface. The value must already be fetched with the various record functions.
* Introspection Engine
  * the logic for separate tables for scalar lists must be removed
  * convert Postgres array columns to correct list field type

**Comment by dpetrick** [comment]
Related: https://github.com/prisma/prisma2/issues/937

**Comment by tomhoule** [comment]
Our PR is open and approved, we should be able to merge it real soon: https://github.com/prisma/prisma-engine/pull/233

**Comment by mavilein** [comment]
Done 🎉
