### ISSUE TITLE
VSCode Extension: Support multiple @@index Statements

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma-engine#211]
It seems like block attributes are checked for uniqueness, even though there can be several of the same category. This should not error: 

<img width="525" alt="Screen Shot 2019-11-07 at 11 51 40" src="https://user-images.githubusercontent.com/16278407/68383030-27cfd000-0155-11ea-8539-64eaef6ba7a4.png">

**Comment by mavilein** [comment]
Found the issue. See this [comment](https://github.com/prisma/prisma-engine/issues/212#issuecomment-560392890) in the sibling issue.

**Comment by matthewmueller** [comment]
This is now fixed in the latest VSCode extension
