### ISSUE TITLE
VSCode Extension: @@unique is not supported yet

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma-engine#212]
The Linter incorrectly warns when using @@unique.

```groovy
model User {
    id Int @id
    firstname String
    lastname String
    @@unique([firstname, lastname], name: "test")
}
```

**Comment by mavilein** [comment]
This is not working in the extension as it is using an outdated [URL for download](https://github.com/prisma/vscode/blob/master/src/install.ts#L21). The right URL can be found in the binaries [spec](https://github.com/prisma/specs/tree/master/binaries).
We should also make sure to bump the plugin version on each release to make sure that users always use a recent version of the `prisma-fmt` binary.

**Comment by matthewmueller** [comment]
Nice debugging! This is now fixed in the latest VSCode extension
