### ISSUE TITLE
Relative database URL paths stopped working

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-engine#213]
```
datasource db {
	provider = "sqlite"
	url      = "file:dev.sqlite"
}
```

The relative URL part doesn’t work anymore with the latest query-engine:

```
❯ ./prisma -p 8405
[/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/4e9084f/src/lib.rs:188] url_str = "file:///dev.sqlite?db_name=dev"
```

Returns this error when sending queries:

```
{
  "errors": [
    {
      "error": "Error in connector: Error querying the database: unable to open database: ///dev.sqlite"
    }
  ],
  "data": {}
}
```

Absolute URLs work.

**Comment by janpio** [comment]
Note: Divy could reproduce this with the new binary again :(

**Comment by pimeys** [comment]
Migration engine hotfix done by @tomhoule. It's already fixed in the user-facing errors branch, but that is not yet merged.

https://github.com/prisma/prisma-engine/pull/216

**Comment by pimeys** [comment]
The query engine fix works.

**Comment by pimeys** [comment]
And I just merged @tomhoule patch.
