### ISSUE TITLE
Benchmark Effects of Removing Implicit Ordering by Id

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma-engine#226]
Subtask for https://github.com/prisma/prisma-engine/issues/178 The behaviour change is explained there.

We are interested in the performance impact of the change. Candidates are Master vs. https://github.com/prisma/prisma-engine/pull/223. 

For this the sql-load-test tool would need to add an additional unique field `unique` to user, post and comments. 

The where filter's selectivity can be adjusted, to not return too much data.

Baseline, should be equivalent:
```
user(where:{name_starts_with: "A"}, orderBy: id_ASC){name}
user(where:{name_starts_with: "A"}, orderBy: id_ASC){name, posts (orderBy: id_ASC){title}}
user(where:{name_starts_with: "A"}, orderBy: id_ASC){name, posts (orderBy: id_ASC){title, comments (orderBy: id_ASC){content}}}
```

These were ordered before, now should be unordered. 
```
user(where:{name_starts_with: "A"}){name}
user(where:{name_starts_with: "A"}){name, posts{title}}
user(where:{name_starts_with: "A"}){name, posts{title, comments{content}}}
```

These were ordered by (unique, id) before, now only by unique.
```
user(where:{name_starts_with: "A"}, orderBy: unique_ASC){name}}
user(where:{name_starts_with: "A"}, orderBy: unique_ASC){name, posts(orderBy: unique_ASC){title}}
user(where:{name_starts_with: "A"}, orderBy: unique_ASC){name, posts(orderBy: unique_ASC){title, comments (orderBy: unique_ASC){content}}}
```

**Comment by pimeys** [comment]
https://www.notion.so/prismaio/Implicit-Ordering-Removal-e4326c1cbf99487e8c48b6e6b6ecd3cf
