### ISSUE TITLE
[Introspection] boolean @id

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engine#258]
phpbb

```
model rzhil_lang {
  lang_author       String  @default("")
  lang_dir          String  @default("")
  lang_english_name String  @default("")
  lang_id           Boolean @id
  lang_iso          String  @default("")
  lang_local_name   String  @default("")

  @@index([lang_iso], name: "lang_iso")
}
```

```
error: Error validating model "rzhil_lang": Invalid ID field. ID field must be one of: Int @id or Int @id @default(`Integer`) for Int fields or String @id or String @id @default(`cuid()`|`uuid()`|`String`) for String fields..
  -->  schema.prisma:316
   | 
315 |   lang_english_name String  @default("")
316 |   lang_id           Boolean @id
317 |   lang_iso          String  @default("")
   | 
```

![image](https://user-images.githubusercontent.com/183673/70332146-3e934080-1841-11ea-8cea-f179b6794ac6.png)

![image](https://user-images.githubusercontent.com/183673/70332173-4eab2000-1841-11ea-9896-dea1bbfd7e38.png)

**Comment by sorenbs** [comment]
### Background

For historic reasons, MySQL treat tinyint(1) and bool, boolean the same.

Material:
- https://dev.mysql.com/doc/refman/8.0/en/numeric-type-overview.html
- https://stackoverflow.com/questions/3751853/boolean-vs-tinyint1-for-boolean-values-in-mysql
- https://www.postgresql.org/message-id/1A478AD5-DC33-40B0-BBD0-BB01A764DA44%40me.com

### Decision

Introspection should behave like this for MySQL:

- tinyint(1) -> Boolean
- tinyint(x) -> Int
- bool -> Boolean
- boolean -> Boolean

### A note on SQLite

SQLite, like MySQL, does not support Boolean. Unlike MySQL, it only supports one number type: `Integer`. For this reason, we can not identify Boolean columns without sampling the data. It is unclear if we should do this.
