### ISSUE TITLE
Implementation of new Id specification

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#274]
**Spec**: The spec has not been written yet. The relevant information can be already found in this [issue comment](https://github.com/prisma/specs/issues/176#issuecomment-561289686).

**Description**: We want to change the representation of ids in the prisma schema. This will also reenable ids that are not auto generated.

**Comment by mavilein** [comment]
## Initial Breakdown of Work Packages
* Datamodel Parser
  * allow `@id` without `@default`
  * disallow simultaneous `@id` and `@unique`
  * disallow `@id` on optional fields
  * allow static default values on id fields
  * implement the new function `autoincrement` that can be used within `@default`
* Migration Engine
  * make sure the PSL is translated correctly into the database schema
* Query Engine
  * no work should be needed here. Some work might be needed in the `DatamodelConverter`.
* Introspection Engine
  * no work should be needed here.

**Comment by do4gr** [comment]
This has been implemented and merged.

**Comment by janpio** [comment]
Can you pinpoint this to a specific `alpha` maybe?
