### ISSUE TITLE
EPIC: Multi field unique 

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engine#28]
**Spec**: The relevant part of the spec on the Prisma Schema Language can be found [here](https://github.com/prisma/specs/tree/master/schema#core-block-attributes).

**Description**: The Prisma Schema Language allows the user to define a combination of fields that should be unique across all records for that model with the `@@unique` directive. It is an implementation detail of a connector how this is implemented. Usually a connector will leverage an index with unique constraint to implement this.

**Example**:
The following example shows a `User` model where the combination of `firstName` and `lastName` is unique.
```graphql
model User {
  id        String @default(cuid())
  firstName String
  lastName  String
  @@unique([firstName, lastName], name: "UniqueFirstAndLastNameIndex")
}
```
## Links to actual Work Packages
* [Datamodel Parser](https://github.com/prisma/prisma-engine/issues/62)
* [Migration Engine](https://github.com/prisma/prisma-engine/issues/59)
* [Query Engine](https://github.com/prisma/prisma-engine/issues/60)
* [Introspection Engine](https://github.com/prisma/prisma-engine/issues/61)

**Comment by mavilein** [comment]
## Initial break down of Work Packages
* Datamodel Parser
  * extend `Model` data structure in `dml` module to store informations on multi field indexes
  * implement new `DirectiveValidator` for `@@unique`
  * test cases:
    * basic happy path
    * name arg must not be optional
    * the directive must not refer to undefined fields
* Migration Engine
  * core: implement new migration steps for indexes (diffing + applying)
  * sql connector:
    * calculation of sql schema
    * diffing of sql schemas
    * add SQL rendering to database step applier

**Comment by mavilein** [comment]
## Links to actual Work Packages
* https://github.com/prisma/prisma-engine/issues/59
* https://github.com/prisma/prisma-engine/issues/60
* https://github.com/prisma/prisma-engine/issues/61

**Comment by mavilein** [comment]
## Open Questions
- [ ] the GraphQL protocol for the communication between photon client and query engine must be defined

**Comment by mavilein** [comment]
I created a specs [issue](https://github.com/prisma/specs/issues/170) about the resulting Photon API. This will probably have influence on our protocol design.

**Comment by dpetrick** [comment]
Query engine changes are merged.
