### ISSUE TITLE
Error message for SQLite shouldn't mention DB server

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-engine#313]
Since SQLite doesn't run a server but just uses a file, the [error message](https://github.com/prisma/prisma-engine/blob/master/libs/user-facing-errors/src/common.rs#L60) shouldn't mention the server. Instead it should read:

```
Database ${database_file_name} does not exist at ${database_file_path}.
```

**Comment by janpio** [comment]
What does the spec say about this error @nikolasburk?

**Comment by nikolasburk** [comment]
It seems to be also wrong in the specs itself: https://github.com/prisma/specs/tree/master/errors#p1003-database-does-not-exist

Should I open a `specs` issue instead (or transfer this one to `specs`)? WDYT @janpio? 🙂

**Comment by janpio** [comment]
Creating one and cross linking to this one (and other way around) would make sure we get to it sooner or later 👍
