### ISSUE TITLE
Error P1006: Say "query engine binary" instead of "Photon binary"

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-engine#314]
The error message for [P1006](https://github.com/prisma/prisma-engine/blob/e7579bd35e0938dbf773f1706c098a0d14a5a038/libs/user-facing-errors/src/common.rs#L115) should say "query engine binary" instead of "Photon binary":

```
Query engine binary for current platform `${platform}` could not be found. Make sure to adjust the generator configuration in the schema.prisma file.
```

**Comment by tomhoule** [comment]
It should probably say `prisma client binary` now, right?

**Comment by nikolasburk** [comment]
I think we'll keep the notion of the "query engine" that's powering Prisma Client, so "query engine binary" should be fine.
