### ISSUE TITLE
Support MariaDB in the migration and introspection engines

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma-engine#317]
Five migration engine tests currently ignore mysql_mariadb. They were probably failing because of a difference in introspection or another minor difference, and shouldn't be much work to fix.

Work packages:

- [x] migration engine (PR: https://github.com/prisma/prisma-engine/pull/349)
- [ ] introspection engine

**Comment by tomhoule** [comment]
We just came across some more weirdness with @do4gr : if you do not provide a default for a column in `CREATE TABLE`, and describe the schema, the introspected default for that column will be `Some("NULL")`. Only on MariaDB.

**Comment by tomhoule** [comment]
MariaDB always appends `DEFAULT NULL` to optional columns (any column that is not `NOT NULL`). In that case, we should infer an optional field with no default.

**Comment by tomhoule** [comment]
@janpio pinging you just so you are aware and in case you want to add that to the next cycle.

**Comment by janpio** [comment]
Indeed - we had a few problems with MariaDB in general with our MySQL schemas. We (@divyenduz mainly) solved that by normalizing on MySQL for our Introspection Databases, but this might have been a limiting decision.

Can you point to or construct a specific schema that is failing? I am sure we can add that to our Introspection testing.

**Comment by tomhoule** [comment]
I haven't spent time investigating the other failing tests in the migration engine test suite, but the following schema:

```sql
CREATE TABLE Users (
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  name VARCHAR(100)
)
```

should be introspected to a prisma schema with `name String? @default("NULL")` if what I wrote above holds.

**Comment by divyenduz** [comment]
Internal note: we now have a RDS running maria DB in our internal introspection analysis infrastructure, I am doing some analysis there, if anyone is interested in knowing/joining.

**Comment by tomhoule** [comment]
Related: https://github.com/prisma/introspection-engine-output/issues/25#issuecomment-571755204

**Comment by tomhoule** [comment]
Status update: all the tests that ignored mariadb in the migration engine now run on mariadb. We haven't looked more in depth or set up testing for mariadb in introspection yet.

**Comment by tomhoule** [comment]
Status update: we haven't worked on testing introspection on mariadb recently afaik.

**Comment by tomhoule** [comment]
With #457, our introspection tests run on MariaDB, so I would say we can considered it supported in the introspection engine. Closing this issue :tada:
