### ISSUE TITLE
All Engines should print commit hash on startup

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#35]
@timsuchanek wants to use this to validate that the javascript code and downloaded engines are in sync. We often had the case that this did not work properly and debugging is unecessarily hard.

**Comment by pimeys** [comment]
We have this now when querying `/server_info` from the query-engine runtime.

**Comment by pimeys** [comment]
We have this also in the command line parameters for query and migration engines:

```
cargo run --bin prisma -- --version
2b78c35cf302bf80ae5aaa863c5eee0d09541f83
```

```
cargo run --bin migration-engine -- --version
2b78c35cf302bf80ae5aaa863c5eee0d09541f83
```

**Comment by pimeys** [comment]
https://github.com/prisma/prisma-engine/commit/fe8f5f767f3122f7b76a64ab13e771c1b822268b

**Comment by janpio** [comment]
How will this be implemented/used?

**Comment by pimeys** [comment]
You just run the binary with `--version` parameter.

**Comment by janpio** [comment]
Ha, yes on the engine side - I was wondering where and how this would be used by @timsuchanek to do what exactly.

**Comment by pimeys** [comment]
When we cut a release, photon asserts the hash and throws if it's not what is expected.

-------- Original Message --------
