### ISSUE TITLE
Performance monitoring: return time spent in the engine

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma-engine#350]
The idea is that the engine returns how many ms it spent on the query and returns that to Photon.

Then in Photon it will be easier to know what time is spent / where, probably the transport layer.

Does that sounds good to you @janpio?

**Comment by janpio** [comment]
Yes, that sounds pretty much what we talked about. @timsuchanek had a few suggestions where we could put it, if I remember correctly some `data` object where this could become a new property or something like that.

**Comment by janpio** [comment]
(Dom and Julius were adamant that `data` object would not be a good place, but suggested a header instead.)
