### ISSUE TITLE
Change an INFO log to a DEBUG log

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-engine#365]
https://github.com/prisma/introspection-engine-output/commit/ced9b566e6d48ecc7fe78cc131d5cc06ca17d310#diff-300421e34c8a93b771fdc84a65d9e964L2

Change this info log to be a debug log. 

![image](https://user-images.githubusercontent.com/746482/72165549-fcbd6300-33c7-11ea-9b67-e6ab3347e0cc.png)

**Comment by divyenduz** [comment]
@do4gr I assume that this is done via https://github.com/prisma/prisma-engine/commit/125571c32d684e10bd77b389801f32c12527f159 ?

**Comment by do4gr** [comment]
Yes, I removed it completely. This was left over from some debugging work.
