### ISSUE TITLE
Migration Engine: Multi field unique

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#59]
Check the related [epic](https://github.com/prisma/prisma-engine/issues/28#issuecomment-535006112) for an initial breakdown of work packages.

Please use supply a more detailed task list in a comment.

**Comment by tomhoule** [comment]
Additional work items we just discussed:

- [ ] Document the migration-connector interface, emphasizing the overall control flow and purpose of operations in the larger context.
- [ ] Rename the `DatabaseSchemaDiffer` and `DatabaseSchemaCalculator` to `SqlSchemaDiffer` and `SqlSchemaCalculator` in `sql-migration-connector`.

**Comment by tomhoule** [comment]
Support for creating and dropping multi-column unique indexes in the migration engine: https://github.com/prisma/prisma-engine/pull/54

**Comment by tomhoule** [comment]
Since #54 is merged, I think we could consider this issue closed.
