### ISSUE TITLE
Query Engine: Multi field unique

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#60]
Check the related [epic](https://github.com/prisma/prisma-engine/issues/28#issuecomment-535006112) for an initial breakdown of work packages.

Please use supply a more detailed task list in a comment.

**Comment by mavilein** [comment]
We can start this after the asyncification of the query engine is done.

**Comment by schickling** [comment]
Once this issue is complete, we need to address https://github.com/prisma/prisma-engine/issues/60 in order to solve https://github.com/prisma/prisma2/issues/773

**Comment by dpetrick** [comment]
Task Breakdown [WIP]:
~Core:~
- [ ] Schema must include a combination fields as unique criteria as per definition of the constraint.
- [ ] Query parsing & validation: Investigate if changes are required.
- [ ] Query graph: Investigate if changes are required.
- [ ] `RecordFinder` (and  possibly `Filter`) structs need to change so it can store a combined unique criteria.
- [ ] Extensive testsuite required to cover all scenarios where multi field uniques can be used.

~Connectors~
- [ ] SQL connector implementation needs to change and adapt the multi field unique queries.
