### ISSUE TITLE
Introspection Engine: Multi field unique

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#61]
Check the related [epic](https://github.com/prisma/prisma-engine/issues/28#issuecomment-535006112) for an initial breakdown of work packages.

Please use supply a more detailed task list in a comment.

**Comment by do4gr** [comment]
Tasks done: 
* verify that the sql-schema-describer can handle compound uniques
* adapt Datamodel calculation so that compound unique indexes are translated to @@unique in a model
* added test cases
