### ISSUE TITLE
Introspection Engine: Multi field id criterion (Multi column PKs) 

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#69]
Check the related [epic](https://github.com/prisma/prisma-engine/issues/29) for an initial breakdown of work packages.

Please use supply a more detailed task list in a comment.

**Comment by do4gr** [comment]
Tasks done: 
* verify that the sql-schema-describer can handle compound ids
* adapt Datamodel calculation so that compound ids are translated to @@id in a model
* add test cases
