### ISSUE TITLE
Build a prototype to compare performance of synchronous and asynchronous database drivers

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#8]
**Goal**: We want to compare the performance of synchronous and asynchronous database drivers.

**Idea**: Build a very simple HTTP server that reads from a Postgres database. Through an interface it should be easy to swap the database driver that is being used.

**Requirements**:
- easily extendable: it must be easy to add new queries to the prototype
  - idea: the server exposes a generic HTTP route for GET `/{path}` where the path is the name of the query to be executed. The server holds a map of static queries mapped to their name. 
- Queries: We can start with some really simple queries that do not require a special database. We should start testing with two simple queries against the `information_schema`. One query that returns one result and one that returns many results.
- benchmark with the Vegeta benchmarking tool
- Build two implementations of the database interface: One based on the sync postgres driver that uses a thread pool to asyncify request processing. Another based on the async postgres driver.

**Interface Draft**:
```rust
pub trait Testee {
    // executes the query with the given name. The result is serialized to JSON and returned.
    fn query(&self, query_name: &str) -> Future<Output = serde_json::Value>;
}
```

**Comment by pimeys** [comment]
The repo is here. https://github.com/pimeys/blocking_test/

**Comment by pimeys** [comment]
What I finished today is a web server that runs in a thread pool, one thread per database query. You can save queries by triggering a `POST` and then execute them by calling `GET`.

Modern stack with the nightly tokio/tide and trait api so I can build the version that runs queries in the current thread asynchronously.

**Comment by pimeys** [comment]
The test results are here.

https://www.notion.so/prismaio/Stress-Testing-82ddd5461e3f446c82f68afffadbec0a

Any comments or do we want more test queries?

**Comment by janpio** [comment]
(Just a FYI: The Notion document is currently publicly visible, without login. Probably doesn't matter for this one fortunately.)

**Comment by pimeys** [comment]
I made it public for the public results. This ticket is public, the code is public so my results and reasoning should also be public!

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pimeys** [comment]
Tested today with a 36-core server, added some pictures and considering the test successful and done.
