### ISSUE TITLE
Fix DeadlockSpec

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#83]
The `DeadlockSpec` in the connector test kit suddenly started failing. The message i see in the logs in the case of Postgres is:
> Error querying the database: db error: FATAL: sorry, too many clients already, application: prisma

It might be a side effect of the latest changes to connection pooling maybe. We should fix this spec.

**Comment by mavilein** [comment]
I had one more look at it and noticed the following things:
- The connections might not be the issue. I noticed that i ended up with tons of zombie prisma processes locally. The connection error seems to be only a sympton.
- After killing the zombies the `CreateMutationSpec` still failed for me locally. The error was a connection refused by the query engine process. In the connector test kit we wait 100ms after starting the query engine before sending queries. This suggests that we have a regression in the startup time. Increasing to 1 second made the spec pass.

**Comment by pimeys** [comment]
Fixed.
