### ISSUE TITLE
Migration Engine: Implement new diffing approach to enable custom types

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#85]
The Migration Engine needs to be able to diff two data models in order to generate the `steps.json` that is central to lift. Currently we diff the data structures in the `dml` module of the `datamodel` crate. I think we should instead diff the data structures of the `ast` module instead. 
This should make our code easier to maintain and at the same time enables diffing of arbitrary directives. This is required to enbale custom types.

**Comment by tomhoule** [comment]
WIP PR: https://github.com/prisma/prisma-engine/pull/97

**Comment by tomhoule** [comment]
This is complete and merged. Discussion continues in https://github.com/prisma/specs/issues/284
