### ISSUE TITLE
Query Engine: Find a replacement for our current logger (performance)

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#91]
This is a followup task from this [issue](https://github.com/prisma/prisma-engine/issues/76).

During benchmarking we found out that our current logger implementation is very slow and in some cases can consume 50% of CPU cycles while processing a simple query. We want to replace the current logger we use. The idea is to evluate tokio tracing for which we need write our own json output formatter.

**Comment by pimeys** [comment]
https://github.com/tokio-rs/tracing/ is very promising from a performance point of view. We need to write a json subscriber to it though.

**Comment by mavilein** [comment]
This is done but not merged to master yet. We first need input from @timsuchanek whether those changes are ok for him. They might affect how the js side must consume the log.

**Comment by timsuchanek** [comment]
This has been merged and is available in alpha.
